name: Deploy Hugo site to Pages

on:
  push:
    branches: ["master"]   # 如果你的源码分支是 master，就改成 master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.139.4'   # 这里改成你用的 Hugo 版本
          extended: true

      - name: Build
        run: hugo -D   # 生成 public 文件夹

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
